### ISSUE TITLE
SfM models

### ISSUE THREAD

**Issue by imelekhov** [ethz-asl/hfnet#1]
Hi,

Thanks for the great work! I am just wondering are you planning to make SfM models of Aachen, RobotCar, and CMU obtained by the proposed method (and SuperPoint) publicly available at some point?

**Comment by Skydes** [comment]
Hi Iaroslav,
Thank your for your interest in our work. Yes, we will make all SfM models publicly available at some point, I just haven't found yet the time to do so :)

**Comment by imelekhov** [comment]
Great! Thanks a lot!

**Comment by dymczykm** [comment]
@imelekhov the models are available now at https://projects.asl.ethz.ch/datasets/doku.php?id=cvpr2019hfnet

**Comment by imelekhov** [comment]
@dymczykm Thanks a lot! Congratulations on the competition!
