### ISSUE TITLE
Hello. About Robotcar evaluation

### ISSUE THREAD

**Issue by shamangary** [ethz-asl/hfnet#10]
Hello. may I ask have you encountered the following problem?
```
# runing the 1st time
[07/12/2019 10:41:54 INFO] Starting to build databases: global: True, local: True
20862it [1:41:06,  3.88it/s]
Killed

# running the 2nd time
[07/12/2019 13:40:17 INFO] Importing global and local databases
Traceback (most recent call last):
  File "hfnet/evaluate_robotcar.py", line 104, in <module>
    loc = Localization('robotcar', args.model, config, build_db=args.build_db)
  File "/store/codeDemo/hfnet-master/hfnet/evaluation/localization.py", line 86, in __init__
    local_db = pickle.load(f)
EOFError: Ran out of input
```

**Comment by shamangary** [comment]
Update:
The cpu memory is not enough, after increase the ram the problem can be resolved.
However, even the error stop the program, the dataset.pkl will still be saved. Therefore, remove the dataset.pkl in 'hfnet/dataset/robotcar/database/....pkl' and run it again the problem will be solved.


However, I have to ask another question is that after I get the dusk query result, the workshop website doesn't support individual subset result (e.g. dusk, sun, night, night-rain). May I ask how do you get that? Thanks

**Comment by Skydes** [comment]
Storing the localization database indeed requires a fair amount of RAM, particularly for RobotCar. Please note that our final entry in the benchmark, contrary to our CVPR paper,  [disables PCA](https://github.com/ethz-asl/hfnet/blob/master/hfnet/evaluate_robotcar.py#L21).

AFAIK the only way to get results for the individual subsets is to directly ask Torsten Sattler @tsattler.

**Comment by tsattler** [comment]
Individual results are shown on the website by clicking on a method to show its details, e.g., https://www.visuallocalization.net/details/12/ .

**Comment by shamangary** [comment]
@Skydes @tsattler Thank you both very much.

However, may I ask one more thing @tsattler? The detail on the website seems to be very good, but it only available for the public submission cases :(. Therefore I cannot test the code before I want to make it public. Is it possible to enable the detail check on the private submission as well? Sorry to bother you guys so many times.

**Comment by tsattler** [comment]
We will work on making this information available for private submissions as well. However, the PhD student who set up the website is currently on an internship and we will not be able to make the changes before he is back in a few months.

**Comment by shamangary** [comment]
Thank you very much again

**Comment by armored-guitar** [comment]
@Skydes 
Hello, i have issue that there not enough RAM for /hfnet/evaluation/utils/db_management/build_localization_dbs for Aachen dataset (I have 16 gb Ram and 32 gb swap). Are there any solutions to use less ram at the moment? It really looks like leak of RAM
