### ISSUE TITLE
 Invalid argument: You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape [?,?,3]

### ISSUE THREAD

**Issue by fengmoumou123** [ethz-asl/hfnet#11]
Dear Author:
when I run the code (db = [hfnet.inference(i) for i in images_db]) of demo.ipynb,it report next error：InvalidArgumentError: 2 root error(s) found.
(0) Invalid argument: You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape [?,?,3]
[[{{node Placeholder}}]]
[[strided_slice_38/_587]]
(1) Invalid argument: You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape [?,?,3]
[[{{node Placeholder}}]]
0 successful operations.
0 derived errors ignored.
May I know how to solve this issue? Many thanks

**Comment by fengmoumou123** [comment]
I already know the reason.。。。

**Comment by Skydes** [comment]
What was the issue?

**Comment by arajzd** [comment]
I'm facing the same problem while running demo, could you share the solution ?

**Comment by fengmoumou123** [comment]
> I'm facing the same problem while running demo, could you share the solution ?
It should be related to the version of Tensorflow.I'm facing the problem while using TF-1.14,then I changed to TF-1.12.It's OK

**Comment by RivaLei** [comment]
in my case, tensorflow=1.12 alrealy
so i create two cells as below which works for me

#cell 1
import tensorflow as tf
import os
os.environ["CUDA_VISIBLE_DEVICES"] = '0'   
config = tf.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.5  
config.gpu_options.allow_growth = True      
sess = tf.Session(config = config)

#cell 2
 tf.reset_default_graph()
