### ISSUE TITLE
Would it be better if i fine-turn the model on my dataset？

### ISSUE THREAD

**Issue by lfydegithub** [ethz-asl/hfnet#12]
Hi, author. thank you for your good job！I have run the hfnet for retrieval and the result is perfectly good. 
But i wanna know that Would it be better if i fine-turn the model on my dataset？
i have no ground truth, learn your code, i find the GT is from NetVLAD and SuperPoint, so i'm not sure it's useful to fine-train...
thanks for your time！

**Comment by Skydes** [comment]
Hi there,

You could indeed run the distillation on your dataset if you believe that it is substantially different from the one we used (Google Landmarks). All is required is a folder of diverse images, ideally in a large number (>200k). 

If you only need retrieval and do not care about efficiency, then you could use NetVLAD. If you still want to use HF-Net, then you could first check that it actually performs sufficiently lower than the baseline NetVLAD+SuperPoint on your kind of data. If so, you can do distillation following the instructions [here](https://github.com/ethz-asl/hfnet/blob/master/doc/training.md) (see also issue https://github.com/ethz-asl/hfnet/issues/5).
