### ISSUE TITLE
Error when training with my own data

### ISSUE THREAD

**Issue by ffrivera0** [ethz-asl/hfnet#13]
Hi, 

I have tried your hfnet model with my own data, and the data structure and model are similar to  Aachen. However, we got an error when doing fast matching, the error is as follows:

***
Traceback (most recent call last):
  File "evaluate_library.py", line 140, in <module>
    loc, queries, query_dataset, max_iter=args.max_iter)
  File "/home/vision/Desktop/vision/hfnet/hfnet/evaluation/localization.py", line 215, in evaluate
    result, stats = loc.localize(query_info, query_data, debug=False)
  File "/home/vision/Desktop/vision/hfnet/hfnet/evaluation/localization.py", line 160, in localize
    debug_dict=matches_data)
  File "/home/vision/Desktop/vision/hfnet/hfnet/evaluation/utils/localization.py", line 96, in match_against_place
    query_desc, place_desc, ratio_thresh, labels=place_lms)
  File "/home/vision/Desktop/vision/hfnet/hfnet/evaluation/utils/descriptors.py", line 111, in fast_matching
    labels_nn = labels[ind]
RuntimeError: index 182649 is out of bounds for dimension 0 with size 2890

***
The shape of labels and ind are:
labels torch.Size([2890])
ind torch.Size([365, 2])

Do you have some advice? By the way, we found that the localdb_hfnet.pkl is much larger than localdb_superpoint.pkl, is that right? Thank you

**Comment by Skydes** [comment]
Hi,

It seems unlikely that you are trying to match against 182649 descriptors, so `ind` should probably not have such high values. Could you check the size of `dist`? If that size is <182649, looks like there could be some overflow issues in topk.

>  By the way, we found that the localdb_hfnet.pkl is much larger than localdb_superpoint.pkl, is that right?

No, that shouldn't be the case, the number of keypoints should be identical, and the descriptors have the same dimensionality. This issue could be related to the error that you describe.

**Comment by ffrivera0** [comment]
Thank you for your advice, the problem has been solved.

**Comment by Talasta** [comment]
I am wondering how did you fixed your error, I have the same one, can't find out how to fix it.

**Comment by Talasta** [comment]
> Thank you for your advice, the problem has been solved.

I have the same issue, what was causing the issue in your case ?

**Comment by Enderych** [comment]
> Thank you for your advice, the problem has been solved.

Hello, how did you made your localdb_hfnet.pkl with your own data? thank you.
