### ISSUE TITLE
dataset documentation in Aachen Day-Night

### ISSUE THREAD

**Issue by zhuixunforever** [ethz-asl/hfnet#14]
Hi, sir. thank you for your good job！
The dataset documentation said Aachen Day-Night need query.db and databases/, but I didn't find it in [the associated website](http://www.visuallocalization.net/)，where did it come from?

**Comment by jingedawang** [comment]
Have the same question.

**Comment by zhuixunforever** [comment]
@jingedawang hello, I think the author made a mistake in the "aachen" of  [dataset documentation](https://github.com/ethz-asl/hfnet/blob/master/doc/datasets.md#datasets). I used the data without query.db, and create an empty folder named 'databases/', and then I successed.

**Comment by Skydes** [comment]
Hi, sorry for the late reply. 

This is indeed a mistake: there should be no `query.db` for Aachen, as the SIFT features for the queries are in the same database `aachen.db` as the DB features. RobotCar has such `query.db` though.

The folder `databases/` is an empty folder that will contain temporary localization databases.
