### ISSUE TITLE
CMU dataset

### ISSUE THREAD

**Issue by ssarahl** [ethz-asl/hfnet#19]
Is it possible to evaluate on the CMU dataset without downloading the Extended CMU dataset? If so, where do the sift_database.db and sift_queries.db files (as listed in the datasets documentation) for each slice exist? When I unzip the sift_descriptors files, there are individual .sift files, but I can't find the .db files.

**Comment by Skydes** [comment]
Sorry for the late reply. This repo provides evaluation for the CMU Seasons dataset, not the extended version. We used [this script](https://github.com/ethz-asl/hfnet/blob/master/colmap-helpers/magic_cmu_to_db.py) to generate a SIFT database from the `.nvm` file. I think that there is no `sift_queries.db` file, this must be a typo in the documentation.

**Comment by ssarahl** [comment]
Thank you for your reply. I used the `magic_cmu_to_db.py` script to generate the `sift_database.db` for each slice, and found the `create_cmu_query_db.py` script for the `sift_queries.db` (not sure if it's needed like you said, but I generated them anyway). Now trying to run the evaluation, hopefully that works!

**Comment by ssarahl** [comment]
When running `evaluate_cmu.py`, I get the following error, which seems to be related to PCA: 

`ValueError: n_components=1024 must be between 0 and min(n_samples, n_features)=446 with svd_solver='full'`

The `min(n_samples, n_features)` number changes depending on the slice. Have you encountered this, or know how to fix the issue? I saw in another issue that you had mentioned possibly disabling PCA?

**Comment by SheldonHS** [comment]
> When running `evaluate_cmu.py`, I get the following error, which seems to be related to PCA:
> 
> `ValueError: n_components=1024 must be between 0 and min(n_samples, n_features)=446 with svd_solver='full'`
> 
> The `min(n_samples, n_features)` number changes depending on the slice. Have you encountered this, or know how to fix the issue? I saw in another issue that you had mentioned possibly disabling PCA?

I've just met the same problem with you, have you solved it now?

**Comment by ssarahl** [comment]
> > When running `evaluate_cmu.py`, I get the following error, which seems to be related to PCA:
> > `ValueError: n_components=1024 must be between 0 and min(n_samples, n_features)=446 with svd_solver='full'`
> > The `min(n_samples, n_features)` number changes depending on the slice. Have you encountered this, or know how to fix the issue? I saw in another issue that you had mentioned possibly disabling PCA?
> 
> I've just met the same problem with you, have you solved it now?

Hi SheldonHS, so sorry, I didn't end up solving this because it wasn't critical for me and moved on to now trying to run hfnet on a custom dataset. Let me know if you solved it though!

**Comment by bxh1** [comment]
> > When running `evaluate_cmu.py`, I get the following error, which seems to be related to PCA:
> > `ValueError: n_components=1024 must be between 0 and min(n_samples, n_features)=446 with svd_solver='full'`
> > The `min(n_samples, n_features)` number changes depending on the slice. Have you encountered this, or know how to fix the issue? I saw in another issue that you had mentioned possibly disabling PCA?
> 
> I've just met the same problem with you, have you solved it now?

Hi SheldonHS，Is it resolved, I have encountered the same problem

**Comment by ssarahl** [comment]
> > > When running `evaluate_cmu.py`, I get the following error, which seems to be related to PCA:
> > > `ValueError: n_components=1024 must be between 0 and min(n_samples, n_features)=446 with svd_solver='full'`
> > > The `min(n_samples, n_features)` number changes depending on the slice. Have you encountered this, or know how to fix the issue? I saw in another issue that you had mentioned possibly disabling PCA?
> > 
> > 
> > I've just met the same problem with you, have you solved it now?
> 
> Hi SheldonHS，Is it resolved？ I also encountered the same problem

Hi @SheldonHS and @bxh1, 

Not sure if you've solved already, I just found that disabling the PCA does in fact allow the evaluation to run! In line 30 of `evaluate_cmu.py` I set `pca_dim` to 0 (instead of 1024).

**Comment by kxhit** [comment]
Hi! After set pca_dim to 0. I got another error.  Could anyone help me? Thanks!
`Traceback (most recent call last):
  File "colmap-helpers/magic_cmu_to_db.py", line 68, in <module>
    main()
  File "colmap-helpers/magic_cmu_to_db.py", line 37, in main
    image_id = db.add_image(name, camera_id)
  File "/dockerdata/xinkong/hfnet/colmap-helpers/internal/db_handling.py", line 178, in add_image
    prior_q[3], prior_t[0], prior_t[1], prior_t[2]))
sqlite3.IntegrityError: UNIQUE constraint failed: images.name`

**Comment by Skydes** [comment]
This is probably a different issue. It says that the entry in the COLMAP database already existed. Maybe the script crashed and you launched it again without deleting the corresponding db?
