### ISSUE TITLE
No trained model

### ISSUE THREAD

**Issue by xxlxsyhl** [ethz-asl/hfnet#2]
Hi, the work is great!  I want to run the demo, but there is no trained model  https://github.com/ethz-asl/hfnet/blob/master/TODO

**Comment by Skydes** [comment]
Hi, the trained model is finally available, see [here](https://projects.asl.ethz.ch/datasets/doku.php?id=cvpr2019hfnet). Apologies for the delay.

**Comment by xxlxsyhl** [comment]
Thanks a lot!
