### ISSUE TITLE
Training dataset

### ISSUE THREAD

**Issue by ChunhuanLin** [ethz-asl/hfnet#23]
Hey, I'm wondering the way to construct training dataset. In your paper, you said that "We thus train on 185k images from the Google Landmarks dataset [34], containing a wide variety of day-time urban scenes, and 37k images from the night and dawn sequences of the Berkeley Deep Drive dataset [54], composed of road scenes with motion blur." However, I find that the images in Google Landmarks is much more than 185k as you described, it turns out 1098462 images in this dataset. So how do you pick out images in the dataset? Why not just use the whole dataset to train? Same question to the bdd dataset. Thx!

**Comment by ChunhuanLin** [comment]
Found the answer in source codes!

**Comment by dblatner** [comment]
@ChunhuanLin : I'd be interested in the solution, can you share your finding? ;-)
