### ISSUE TITLE
Modification of MobileNet V2

### ISSUE THREAD

**Issue by ChunhuanLin** [ethz-asl/hfnet#24]
I find that you change the output channels of layer 6 and 7 to 64 and 128, respectively. Why are you doing this?
Thanks!

**Comment by QsingHuan** [comment]
Not only layer 6 and 7 are modified, there are many differences between the paper and the code. It seems that the author tends to use a bigger network, what is the reason? Looking forward to your reply.

**Comment by sarlinpe** [comment]
We introduced this to avoid bottlenecks in the number of channels. In retrospect, we could have done more architecture search to obtain a more compact network. Sorry if there are small implementation discrepancies - always refer to the code when in doubt. Closing this issue for now - feel free to reopen.
