### ISSUE TITLE
Aachen Dataset

### ISSUE THREAD

**Issue by JingruiYu** [ethz-asl/hfnet#27]
I download the Aachen dataset on the reference web.  However, I cannot find the models folder and the corresponding contents, such as  cameras.bin, images.bin, and points3D.bin. Could you tell me where to get these files? Thanks!

**Comment by Skydes** [comment]
The original dataset and our SfM models are hosted on different websites. More details [here](https://github.com/ethz-asl/hfnet#required-assets).

**Comment by JingruiYu** [comment]
Thanks，the problem is solved.

**Comment by armored-guitar** [comment]
@JingruiYu excuse me, have you met any problems trying to build databases for aachen?
