### ISSUE TITLE
Model Release

### ISSUE THREAD

**Issue by ckcraig01** [ethz-asl/hfnet#3]
Thanks for your great work.
I saw that there is a closed sfm model question. Is that related this part?
 
"We provide SfM models of Aachen, RobotCar and CMU built with HF-Net/SuperPoint. Download and unpack the HF-Net weights in $EXPER_PATH/hfnet/"

**Comment by ckcraig01** [comment]
Hi, Thanks!

I have seen this part in the paper:

The process is as follows: i) we perform 2D-2D matching between reference frames using our
features and an initial filtering ratio test; ii) the matches are
further filtered within COLMAP using two-view geometry;
iii) 3D points are triangulated using the provided ground
truth reference poses. Those steps result in a 3D model with
the same scale and reference frame as the original one.

We wonder will this flow be released that we could try to examine on other datasets?

**Comment by Skydes** [comment]
Hi, thank your for your interest in our work. The SfM models are finally available [here](https://projects.asl.ethz.ch/datasets/doku.php?id=cvpr2019hfnet). Regarding the process to build new SfM models, it is explained in details in `colmap-helpers/README.md`.
