### ISSUE TITLE
Local feature matching

### ISSUE THREAD

**Issue by lidongjiangBJTU** [ethz-asl/hfnet#30]
Hello, excellent work! 
I have a minor question when I read your paper. 
in the paper, "Local feature matching. For each place, we successively match the 2D keypoints detected in the query image to the 3D points contained in the place" . 
May I ask that which method was adopted in the process of 2d and 3d matching ? because it only expressed as successfully matched and not mentioned matching algorithms.
Looking forward your reply.

**Comment by Skydes** [comment]
We use a brute force nearest neighbor matcher (see [here](https://github.com/ethz-asl/hfnet/blob/b0400570cca78638ff97e8f2db2d2b1185abd0fd/hfnet/evaluation/utils/localization.py#L95)).
