### ISSUE TITLE
Aachen evaluation RAM

### ISSUE THREAD

**Issue by armored-guitar** [ethz-asl/hfnet#31]
Hello, i have issue that there not enough RAM for /hfnet/evaluation/utils/db_management/build_localization_dbs for Aachen dataset (I have 16 gb Ram and 32 gb swap). Are there any solutions to use less ram at the moment? It really looks like leak of RAM

**Comment by Skydes** [comment]
You could maybe cut the localization database in chunks and avoid loading it entirely at once - this is not implemented in the code.
