### ISSUE TITLE
hfnet feature matching VS colmap sift feature matching 

### ISSUE THREAD

**Issue by yuancaimaiyi** [ethz-asl/hfnet#32]
@Skydes ![siftAndSuperpoint](https://user-images.githubusercontent.com/28293910/75136872-fa695b00-5720-11ea-9059-05c2454b97e2.png)
hello,as you sea ,In the picture ,the up is the result of " colmap sift feature matching ",the bottom is the result of "hfnet feature matching ". There are a lot of mismatches about hfnet feature matching .
A lot of papers show that superpoint is better than sift, so I'm confused . Am I wrong?

**Comment by Skydes** [comment]
In this easy example, SIFT produces more matches because it detects more keypoints. For difficult cases like day-night localization, SIFT is poorly repeatable and has weak descriptors - it thus produces much fewer correct matches than SuperPoint.
