### ISSUE TITLE
Unable to load the model

### ISSUE THREAD

**Issue by Zumbalamambo** [ethz-asl/hfnet#34]
It fires up the following error while trying to load the model
`

> `
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'Resampler' in binary running on DESKTOP. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.`

`

**Comment by Skydes** [comment]
The code uses the [tf.contrib.resampler](https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/contrib/resampler), which does not seems to have a different [name](https://www.tensorflow.org/addons/api_docs/python/tfa/image/resampler) in TF >=2.0. I did not test this code for TF >=2.0 and do not plan to make it compatible.

**Comment by schmidtp1** [comment]
i'm having the same issue w/ tf 1.12.0
