### ISSUE TITLE
how to build hloc-cpp?

### ISSUE THREAD

**Issue by tiger20** [ethz-asl/hfnet#36]

**Comment by Skydes** [comment]
I do not actively support the C++ implementation, but you can try to build it. We use Catkin, and the dependencies are mentioned in [package.xml](https://github.com/ethz-asl/hfnet/blob/master/hloc-cpp/package.xml). Note that the C++ version does not support GPU feature matching.

**Comment by tiger20** [comment]
@Skydes thank you for your reply
