### ISSUE TITLE
Using matching method in hfnet to replace 2d-2d matching in colmap

### ISSUE THREAD

**Issue by tiger20** [ethz-asl/hfnet#37]
I noticed that the matching method used in hfnet is quite efficient, it pile up the descriptors of several retrieval images into a big matrix and then match with the query descriptor matrix.after that it apply low ratio test to select valid matches. In this way, multiple database images can match  with the query image in the same time.However , in colmap, when we use colmap sequential_mathcer, it only match one image pair at a time, which is slow compared to the matching method in hfnet.Is there any way to accelerate the matcher in colmap like the way hfnet did?

**Comment by Skydes** [comment]
As far as i know COLMAP does support batched descriptor matching on GPU. Maybe you are referring to our reconstruction code, which I admit is not the most efficient. I plan to release a new codebase to do all of this in a much simpler and smoother way, stay tuned.

**Comment by Skydes** [comment]
If you're looking for a fast codebase for SfM reconstruction with SuperPoint/SuperGlue, check out my new hloc toolbox: https://github.com/cvg/Hierarchical-Localization
