### ISSUE TITLE
ValueError: not enough values to unpack (expected 4, got 0)

### ISSUE THREAD

**Issue by zzl20** [ethz-asl/hfnet#38]
Hi, when i run evaluate_aachen.py, there are some errors as follow:
![p4](https://user-images.githubusercontent.com/26411422/83475141-5120c680-a4c0-11ea-9ea3-909c59a5fe13.png)
how to solve this problem,  Look forward to your reply ！

**Comment by Skydes** [comment]
Do you happen to have any empty lines in `day_time_queries_with_intrinsics.txt` or `night_time_queries_with_intrinsics.txt`? this should not happen and the code does not check for this.

**Comment by zzl20** [comment]
> Do you happen to have any empty lines in `day_time_queries_with_intrinsics.txt` or `night_time_queries_with_intrinsics.txt`? this should not happen and the code does not check for this.

Thank you very much, there are some empty lines in night_time_queries_with_intrinsics.txt, now, it is ok!
