### ISSUE TITLE
How to build my own sfm mode

### ISSUE THREAD

**Issue by zzl20** [ethz-asl/hfnet#39]
hi, if i want to use my own data to build a new sfm mode, how to do that?
Is it in the file "colmap-helpers"? Can you say some of the details right？Thank you very much

**Comment by Skydes** [comment]
The scripts in `colmap-helpers` expect an existing SfM model with ground truth poses, and thus only perform triangulation. In your case, you will need to run the mapper to estimate the poses as well. This repo should have what you need: https://github.com/ahojnnes/local-feature-evaluation

I will release some tools to easily do SfM with SuperPoint/SuperGlue, but it's not ready yet.

**Comment by zzl20** [comment]
> The scripts in `colmap-helpers` expect an existing SfM model with ground truth poses, and thus only perform triangulation. In your case, you will need to run the mapper to estimate the poses as well. This repo should have what you need: https://github.com/ahojnnes/local-feature-evaluation
> 
> I will release some tools to easily do SfM with SuperPoint/SuperGlue, but it's not ready yet.

According to the paper,  if i want to run localization use my own data, i need a SuperPoint sfm_modle, i try to use colmap to build that modle using my own data,   " https://github.com/ahojnnes/local-feature-evaluation", this can help me build a SuperPoint sfm_model?

**Comment by Skydes** [comment]
Yes.

**Comment by Skydes** [comment]
Hi, I just released a toolbox for visual localization and SfM with SuperGlue: https://github.com/cvg/Hierarchical-Localization You should be able to use it on your own data - please let me know if the documentation is unclear.
