### ISSUE TITLE
When re-generating SfM via superpoint, the number of pointclouds is too little so it raise some unexpected errors!

### ISSUE THREAD

**Issue by LimHyungTae** [ethz-asl/hfnet#42]
Hello, Mr. Sariln! :) First, thanks for giving these high-quality codes.

We want to employ your code on our environment, so we tested codes in the colmap-helpers on Aachen dataset  before porting, yet it does not work.
Specifically, we followed the colmap-helpers instruction that written on the README.md, so tried to re-construct SfM model via superpoint, but the SfM have little pointclouds (almost 80,000 3-D points) compared to the provided SfM model (almost 680,000 3-D points).
So, I hope to get some information to generate SfM model from superpoint in detail to use it on the other dataset.
Thanks in advance!

**Comment by Skydes** [comment]
Hi, thank you for you interest. It is difficult for me to provide support with so little information. I know several people that successfully used the provided scripts to run SfM without much problems. I recommend rerunning the reconstruction again and paying attention to any error messages. I will release in the next weeks some tools to run SfM reconstruction with SuperPoint and [SuperGlue](https://psarlin.com/superglue/), but it is not ready yet.

**Comment by LimHyungTae** [comment]
I appreciate your quick reply, and I found the fact that the number of 3-D pointclouds increases when we set appropriate NMS value of superpoint! In detail, the number of points become almost 80,000 -> 235,562. So it might indicate that redundant keypoints gathered by superpoint (originally, NMS value was set to 0) hinder the matching of images. Even though it is improved, yet the # of points are still few in number compared to pre-constructed SfM model (680,000) that you provide. Do you have any insight to resolve this issue? Thank you and have a nice weekend :)

**Comment by LimHyungTae** [comment]
![model_img](https://user-images.githubusercontent.com/35317311/85131460-d272aa00-b271-11ea-9193-6d49956352c1.png)
=> SfM that you uploaded
![스크린샷, 2020-06-19 21-13-47](https://user-images.githubusercontent.com/35317311/85131486-def70280-b271-11ea-8a7d-1bad09764607.png)
=> Ours :(

**Comment by Skydes** [comment]
What version of Tensorflow and PyTorch are you using? Can you visualize keypoints in the npz files?

**Comment by LimHyungTae** [comment]
I use TF-GPU 1.15 and 1.3 pytorch. 
![118](https://user-images.githubusercontent.com/35317311/85205033-72eccb00-b353-11ea-89b1-0f909ead86f3.png)
And visualized points seem to be reasonable, as far as I understood (actually, some points are redundant). Is there any mistake?? We just revise NMS option 0 to 4. I upload visualized imgs and npz files also.

**Comment by LimHyungTae** [comment]
[1.zip](https://github.com/ethz-asl/hfnet/files/4808108/1.zip)
[2.zip](https://github.com/ethz-asl/hfnet/files/4808109/2.zip)

**Comment by LimHyungTae** [comment]
[3.zip](https://github.com/ethz-asl/hfnet/files/4808110/3.zip)
[4.zip](https://github.com/ethz-asl/hfnet/files/4808111/4.zip)

**Comment by Skydes** [comment]
The detections look reasonable - the NMS should instead be set to 4. Checking the matching would help, there is debug flag in `match_features_with_db_prior.py`- it will plot the matches.

**Comment by LimHyungTae** [comment]
When we checked the results of matchings, the matchings' are fine. We suspect several factors: i) in `python3 update_db_with_nvm_intrinsics.py`, should we revise focal length since the images are resized to 960? ii) in `colmap feature_importer`, should we resize the images to set correct relationships btw keypoints and images (yet I think images are only employed when colorization)?

**Comment by LimHyungTae** [comment]
![0](https://user-images.githubusercontent.com/35317311/85365766-f6c7d280-b560-11ea-981f-40d422e4e48d.png)
![50](https://user-images.githubusercontent.com/35317311/85365777-f92a2c80-b560-11ea-93a5-291642fd96c4.png)
![1050](https://user-images.githubusercontent.com/35317311/85365791-fe877700-b560-11ea-8002-088fd1da4483.png)
![3250](https://user-images.githubusercontent.com/35317311/85365803-03e4c180-b561-11ea-83f1-88c6baeb9232.png)
![3850](https://user-images.githubusercontent.com/35317311/85365816-0b0bcf80-b561-11ea-9805-409fb17957ac.png)

**Comment by LimHyungTae** [comment]
Oops, I found why the result is off! How silly I am....I skipped `colmap-helpers/export_for_sfm.py` procedure...lol. Sorry for bothering you and I really appreciate your kind help! Thank you. :)

**Comment by Skydes** [comment]
Glad you found the issue, I hope the next steps will go smoothly for you! :)
