### ISSUE TITLE
dense directory is missing in sfm dataset

### ISSUE THREAD

**Issue by feixue94** [ethz-asl/hfnet#44]
hi, thank you for your excellent work. it seems that only rgb images can be found in the testing sequences of sfm dataset and the "dense" directories are missing.

**Comment by Skydes** [comment]
Hi. The test SfM dataset is indeed not public. Since this paper was published, a new benchmark was created using the same test set. Please instead use the evaluation pipeline of the [image matching challenge](https://vision.uvic.ca/image-matching-challenge/).
