### ISSUE TITLE
Is it suitable to train the HF-Net using other common datasets instead of Googble Landmarks/BDD?

### ISSUE THREAD

**Issue by CanboYe** [ethz-asl/hfnet#46]
When training HF-Net with multi-task distillation, is it feasible to train the HF-Net using some other common datasets instead of Googble Landmarks/BDD? Because we actually don't need labeled data here and is it better to train the whole HF-Net using some other data according to our application scenario?

For example, if we want to deploy it on autonomous vehicles, we could train a HF-Net using a larger training set from Kitti or RobotCar.

**Comment by Skydes** [comment]
Yes, HF-Net can be trained on pretty much any collection of images depending on your target domain: autonomous driving, indoor data, etc. Of course the performance will always be upper bounded by the teacher network.

**Comment by CanboYe** [comment]
Thanks!
