### ISSUE TITLE
Is it possible to do the online localization pipeline with HF-Net without GPU?

### ISSUE THREAD

**Issue by CanboYe** [ethz-asl/hfnet#49]
Many mobile devices don't have GPU installed, so I was wondering if it is possible to do the online localization pipeline with HF-Net without GPU. And how much the performance of HF-Net would be impacted comparing to those handcrafted methods like SIFT?

**Comment by sarlinpe** [comment]
Our paper shows a comparison between HFNet, NetVLAD+SuperPoint, and NetVLAD+SIFT - see Table 3 and Figure 4. Modern mobile phones often come with embedded deep learning accelerators, on which small networks like MobileNet can run reasonably fast. If this is not possible, lightweight handcrafted features, like ORB or BRISK, could be used - but their performance is much lower. The large memory footprint of the SfM model and database is a bigger limitation than the network inference.
