### ISSUE TITLE
hfnet inference with C++

### ISSUE THREAD

**Issue by TurtleZhong** [ethz-asl/hfnet#50]
Hi everyone, Thanks for @Skydes 's great work. hf-net is a state-of-the-art method in visual localization. But the origin inference code is written with Python. I modified the inference part with c++, also provide a docker image, I guess it is more convenient integration into other projects. (slam  or vio system)

The code is here:
https://github.com/TurtleZhong/hfnet_ros

**Comment by sarlinpe** [comment]
Cool work, thanks for sharing it! Glad to see it running so fast. I am now closing this issue - feel free to reopen.
