### ISSUE TITLE
About disstillation in the global descriptor

### ISSUE THREAD

**Issue by YellowBe** [ethz-asl/hfnet#54]
Hello, thanks for your paper! I just start to learn knowledge distillation, I want to know how to get the loss of global descriptor,  does it works like get a vlad result in the student model and  get another one in the teacher model(netvlad), and then calculate the MSE of them?

**Comment by sarlinpe** [comment]
Yes. Please refer to the paper or to the code for more details.

**Comment by YellowBe** [comment]
sorry~ i mean how do you do the distillation? what is the algorithm in the code? is it just like the algorithm in the paper "Distilling the Knowledge in a Neural Network"...

**Comment by sarlinpe** [comment]
Yes. This is a vanilla application of distillation, with a fixed teacher and trainable student.
