### ISSUE TITLE
why triangulate the aachen 3D model according to matches instead of using 3d points provided?

### ISSUE THREAD

**Issue by TxT1212** [ethz-asl/hfnet#59]
Hello!
I noticed in ezxr/hfnet/colmap-helpers/example_scripts/run_aachen_sift.sh:

1.  you triangulate the model. However, there are 3d points provided by aachen dataset, why not use them instead?
2.  you update db with nvm intrinsics, however in aachen dataset readme.md [https://data.ciirc.cvut.cz/public/projects/2020VisualLocalization/Aachen-Day-Night/README_Aachen-Day-Night.md](url) 

> Please note that the intrinsic parameters stored in the `.nvm`, `.out`, and `.info`  files might 
differ. You should ignore the intrinsics in these files and only use the ones provided in 
`database_intrinsics.txt`.

I am confused, please help.

**Comment by sarlinpe** [comment]
We might use a different SIFT implementation than the dataset authors, so we triangulate a new SIFT model to avoid inconsistency. The intrinsics in `database_intrinsics.txt` are indeed more accurate - please refer to [hloc](https://github.com/cvg/Hierarchical-Localization) for a better pipeline.

**Comment by TxT1212** [comment]
thank you for your reply. Helps a lot.
