### ISSUE TITLE
setup problem, no files/directory from PKG-INFO

### ISSUE THREAD

**Issue by lucaferranti** [ethz-asl/hfnet#6]
Hi,

I am trying to setup hfnet on my pc but when running make install, but I ran into the following problem

pip3 install -e setup/
Obtaining file:///mnt/c/Users/Luca/OneDrive%20-%20TUNI.fi/TTY/diplomityo/hfnet/setup
No files/directories in /mnt/c/Users/Luca/OneDrive%20-%20TUNI.fi/TTY/diplomityo/hfnet/setup (from PKG-INFO)
makefile:2: recipe for target 'install' failed
make: *** [install] Error 1

any suggestions how to fix this?

**Comment by hwjwill** [comment]
maybe try `python3 hfnet/setup.py build` and then `python3 hfnet/setup.py install` after running the setup.sh script?

**Comment by Skydes** [comment]
Hi there, this indeed seems to be a bug. I moved `setup.py` to the repo root, see PR https://github.com/ethz-asl/hfnet/pull/7.
