### ISSUE TITLE
RobotCar Seasons evaluation issues

### ISSUE THREAD

**Issue by yzssik** [ethz-asl/hfnet#63]
Hello ,paul.

I found that the evaluation results of RobotCar Seasons in your paper are for each different condition, but when I submit it in visuallocalization.net, I can only upload all night conditions and all day conditions. How did you do that? To be assessed separately?

**Comment by haoweiz23** [comment]
I meet the same problem. Have you figured out this problem now? @yzssik

**Comment by yzssik** [comment]
Hi,
You can get separate results for different weather conditions by submitting them separately, as shown in the picture below. After I get the results of the dust, night, night-rain, and sun conditions, I upload them to the website respectively. I submitted the result that I chose the RobotCar-Seasons v2 dataset and got RobotCar all day 17.2 / 25.0 / 27.5. The results of night-rain, sun, and dust are much worse than the author's. I consulted the website and got a reply that the current website can only calculate the posture of the rear camera. I guess that's one of the reasons for such poor results.I hope this can help you.



And I see you have questions about the training process. Can you download the Google Landmarks&nbsp;dataset according to the code provided by the original author? I'm having trouble trying to download them, and I'm guessing the reason is that I can't get a stable connection to Google's servers in China. Could you please provide me the training dataset? I will be very grateful.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ethz-asl/hfnet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月12日(星期二) 上午10:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ethz-asl/hfnet] RobotCar Seasons evaluation issues (#63)





 
I meet the same problem. Have you figured out this problem now? @yzssik

**Comment by yzssik** [comment]
Hi,&nbsp;
Sorry for the inaccuracy of the last reply. I found that opening&nbsp; MY SUBMISSIONS and clicking on the name of the method you submitted will open a new web page that will detail the results under each condition. And I see you have questions about the training process. Can you download the Google Landmarks dataset according to the code provided by the original author? I'm having trouble trying to download them, and I'm guessing the reason is that I can't get a stable connection to Google's servers in China. Could you please provide me the training dataset? I will be very grateful.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zoey"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月30日(星期六) 晚上9:38
***@***.***&gt;;

主题:&nbsp;回复： [ethz-asl/hfnet] RobotCar Seasons evaluation issues (#63)



Hi,
You can get separate results for different weather conditions by submitting them separately, as shown in the picture below. After I get the results of the dust, night, night-rain, and sun conditions, I upload them to the website respectively. I submitted the result that I chose the RobotCar-Seasons v2 dataset and got RobotCar all day 17.2 / 25.0 / 27.5. The results of night-rain, sun, and dust are much worse than the author's. I consulted the website and got a reply that the current website can only calculate the posture of the rear camera. I guess that's one of the reasons for such poor results.I hope this can help you.



And I see you have questions about the training process. Can you download the Google Landmarks dataset according to the code provided by the original author? I'm having trouble trying to download them, and I'm guessing the reason is that I can't get a stable connection to Google's servers in China. Could you please provide me the training dataset? I will be very grateful.





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "ethz-asl/hfnet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月12日(星期二) 上午10:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ethz-asl/hfnet] RobotCar Seasons evaluation issues (#63)





 
I meet the same problem. Have you figured out this problem now? @yzssik

**Comment by haoweiz23** [comment]
> Hi,&nbsp; Sorry for the inaccuracy of the last reply. I found that opening&nbsp; MY SUBMISSIONS and clicking on the name of the method you submitted will open a new web page that will detail the results under each condition. And I see you have questions about the training process. Can you download the Google Landmarks dataset according to the code provided by the original author? I'm having trouble trying to download them, and I'm guessing the reason is that I can't get a stable connection to Google's servers in China. Could you please provide me the training dataset? I will be very grateful.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zoey" ***@***.***&gt;; 发送时间:&nbsp;2022年4月30日(星期六) 晚上9:38 ***@***.***&gt;; 主题:&nbsp;回复： [ethz-asl/hfnet] RobotCar Seasons evaluation issues (#63) Hi, You can get separate results for different weather conditions by submitting them separately, as shown in the picture below. After I get the results of the dust, night, night-rain, and sun conditions, I upload them to the website respectively. I submitted the result that I chose the RobotCar-Seasons v2 dataset and got RobotCar all day 17.2 / 25.0 / 27.5. The results of night-rain, sun, and dust are much worse than the author's. I consulted the website and got a reply that the current website can only calculate the posture of the rear camera. I guess that's one of the reasons for such poor results.I hope this can help you. And I see you have questions about the training process. Can you download the Google Landmarks dataset according to the code provided by the original author? I'm having trouble trying to download them, and I'm guessing the reason is that I can't get a stable connection to Google's servers in China. Could you please provide me the training dataset? I will be very grateful.
> ------------------ 原始邮件 ------------------ 发件人: "ethz-asl/hfnet" ***@***.***&gt;; 发送时间:&nbsp;2022年4月12日(星期二) 上午10:37 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [ethz-asl/hfnet] RobotCar Seasons evaluation issues (#63) I meet the same problem. Have you figured out this problem now? @yzssik — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

Sorry for the late reply.  I have access to the oversea servers, so I have not connection problem.
