### ISSUE TITLE
undefined variables output_types, output_shape

### ISSUE THREAD

**Issue by HyuncheolJeon** [ethz-asl/hfnet#67]
I'm trying to train HFNet.
When I ran train.py, I got a error message below
 " AttributeError: 'MapDataset' object has no attribute 'output_types' "
It occurs in distillation.py, line 142.
I commented out this part and rerun the code. I got a error message in base_model.py, line 248
 " AttributeError: 'PrefetchDataset' object has no attribute 'output_types' "
I tried to find the variables "output_types", "output_shapes", but I think these are not defined.
How should I handle these variables?

Thank you

**Comment by alynneholmstrom** [comment]
How did you fix this problem? I am having the same error " AttributeError: 'PrefetchDataset' object has no attribute 'output_types'" along with output_shapes.
