### ISSUE TITLE
Config issue

### ISSUE THREAD

**Issue by shamangary** [ethz-asl/hfnet#8]
Hello! Great work.

Just trying to follow the instruction but run into many troubles. 
1. The following instructions seems to be very similar 
```
# instruction
Download the trained model here and unpack it in $EXPER_PATH/saved_models/.

Required assets
Download and unpack the HF-Net weights in $EXPER_PATH/hfnet/. 
```
After I download the hfnet from the link (https://projects.asl.ethz.ch/datasets/doku.php?id=cvpr2019hfnet) and unpack it, I only get saved_models folder. It seems like **'unpack the HF-Net weights in $EXPER_PATH/hfnet/'** is unclear to me.

2. Follow up question
```
# Running the command
python3 hfnet/export_predictions.py \
    'hfnet/configs/hfnet_export_aachen_db.yaml' \
    'superpoint/aachen' \
    --exper_name hfnet \
    --keys keypoints,scores,local_descriptor_map[,global_descriptor]
# Error
hfnet/export_predictions.py:30: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
Traceback (most recent call last):
  File "hfnet/export_predictions.py", line 42, in <module>
    with open(Path(EXPER_PATH, exper_name, 'config.yaml'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'experiments/hfnet/config.yaml'

```

https://github.com/ethz-asl/hfnet/blob/master/hfnet/export_predictions.py#L42
```
with open(Path(EXPER_PATH, exper_name, 'config.yml'), 'r') as f:
```
It seems like there is no 'config.yml' anywhere.
So I try to find the similar file which is under the folder (https://github.com/ethz-asl/hfnet/tree/master/hfnet/configs) and I can find many '.yaml' files.
However, it is still unclear which one should I adopt in each circumstances.

Thank you

**Comment by hwjwill** [comment]
Disclaimer: I'm not the author but got things working

1. $EXPER_PATH is a path you defined through setup.sh. For example, my $EXPER_PATH is `/home/ubuntu/dev/HFNet/experiment/`, then save the unpacked `saved_models` folder in $EXPER_PATH so it will looks like `/home/ubuntu/dev/HFNet/experiment/saved_models/hfnet/saved_model.pb` and `/home/ubuntu/dev/HFNet/experiment/saved_models/hfnet/variables/`

2. Depending whether you want to evaluate using NetVLAD + Superooint or HFNet. For example, if my global method is NetVLAD, then when I generate global descriptor, I will want to use config fire with netvlad_export_[dataset_name].yaml. If I want to use Superpoint as local matching descriptor, when I generate local descriptor, I will want to use superpoint_export_[dataset_name]_[db, query].yaml

**Comment by Skydes** [comment]
Hi @shamangary, thank you for your interest!

1. This is clearly a mistake from my side, [`hfnet_tf.tar.gz`](http://robotics.ethz.ch/~asl-datasets/2019_CVPR_hierarchical_localization/hfnet_tf.tar.gz) should have also contained a directory `hfnet/` with the products of the training: weights (before export to a saved model), configuration (this `config.yaml`), logs, and Tensorboard summaries.

2. `export_predictions.py` is looking for the trained weights, which were indeed missing. There was also a typo in the extension of the config file, I just fixed this in https://github.com/ethz-asl/hfnet/pull/9.

I updated the tarball, let me know if that works for you.

@hwjwill Thanks for helping out :)

**Comment by shamangary** [comment]
Thank you. It seems like it's working now. :dancer:

**Comment by ynma-hanvo** [comment]
sorry to ask  another simple question,  what is the difference between the hfnet folder  and the saved_models folder, I checked the demo.py is actually using the saved_models

**Comment by ynma-hanvo** [comment]
actually what I want to do is to export an hfnet model with all possible outputs like local_descriptors , global_descriptors, keypoints,   how can I modify the config.yaml for it.
